### ISSUE TITLE
SOF or OEF

### ISSUE THREAD

**Issue by zcao** [foo123/editor-grammar#3]
I see in the document that ^^ defines start of file

I tried to define a language that only contains foo and bar
But the input is "foo bar foo bar", the second "foo bar" is still matched and styled, the ^^ does not seemed to work.

**Comment by foo123** [comment]
You should post the grammar to see how you have done this, for example the following should work

```javascript
"lang" : "(^^ 'foo' 'bar')?"
```


This should match only the first line which should have 'foo' and 'bar' tokens.

Sorrry for late reply, but have other problems right now
